version: '3.8'

services:
  weatherbycep:
    build: .
    ports:
      - "8080:80"
    environment:
      - PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/weatherbycep/01310100"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
