name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v
      
    - name: Run tests with coverage
      run: go test -cover
      
    - name: Run benchmark
      run: go test -bench=.
      
    - name: Build application
      run: go build -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t weatherbycep .
      
    - name: Test Docker image
      run: |
        docker run -d -p 8080:80 --name test-container weatherbycep
        sleep 10
        curl -f http://localhost:8080/weatherbycep/01310100 || exit 1
        docker stop test-container
        docker rm test-container
